language: python
python:
 - "3.5"

# command to run tests
script:
 - python -m unittest test_triangle_classification

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
